[build]
  # Comando para construir tu proyecto
  command = "npm run build"
  # El adapter-netlify genera la salida en "build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

# Redirecciones necesarias para manejar todas las rutas de SvelteKit
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
